name: DockerImage

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          make docker-build

      - name: Push image
        run: |
          make docker-upload
