name: Release

on:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.REPO }}
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO }}

      - name: Set up GitHub Token
        run: |
          git config --global user.name "Helmut Konrad Schewe"
          git config --global user.email "helmutus@outlook.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/cobdh/collection.git

      - name: Release and Push
        run: |
          make docker-release

      - name: Push commit and tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push origin main
          git push origin --tags
